Gamepad class reworked
lsd-maddrive/bb_project pull request #3
Opened 2021-07-24 16:05 UTC by Doraepod

На железе еще не проверял. Возможно надо с обработкой эксепшнов что-то изменить. Сливать пока не стоит, наверное, но если будет время посмотри мои писульки, пожалуйста.

2021-07-25 12:16 UTC, serykhelena requested changes

2021-07-25 12:16 UTC, serykhelena commented on python/gamepad/src/xbox_one.py
> +            if ("Xbox" in i.name) or ("X-Box" in i.name):
А если не найдёт устройство? Может добавить обработку?

2021-07-25 12:16 UTC, serykhelena commented on python/gamepad/src/xbox_one.py
> +    def __init__(self):
мне кажестя, в этот класс полезно было бы логгер добавить через модуль logging

2021-07-25 12:16 UTC, serykhelena commented on python/gamepad/src/xbox_one.py
> +def main():
Эту функцию из класса лучше перенести в скрипт test_gamepad.py или что-то такое. `if __name__ == "__main__"` тоже. Или начать писать юнит тесты через pytest - этот вариант даже лучше, как мне кажется (=

2021-07-27 14:24 UTC, serykhelena requested changes

2021-07-27 14:24 UTC, serykhelena commented on python/gamepad/src/xbox_one.py
> +logging.basicConfig(
в файле класса (исходном) не очень принято задавать конфиг логгера. Это делается из "исполняемого" скрипта. Таким образом, можно управлять конфигом в одном месте, а не бегать по всем исходникам

2021-07-27 14:24 UTC, serykhelena commented on python/gamepad/src/xbox_one.py
> +logger = logging.getLogger(__name__)
объект логгера (как мне кажется) лучше засунуть внутрь класса. Что-то типа `self._logger = logging.getLogger(self.__class__.__name__)`

2021-07-27 14:24 UTC, serykhelena commented on python/gamepad/src/xbox_one.py
> +            return
мне кажется, вместо return лучше сделать raise Exception, причём какое-нибудь определённое, типа ValueEror или что-то подобное

2021-07-27 14:56 UTC, Doraepod commented on python/gamepad/src/xbox_one.py
> +def main():
Готово

2021-07-27 14:59 UTC, Doraepod commented on python/gamepad/src/xbox_one.py
> +            return
Я сейчас сделал при старте исполняемого скрипта напоминалку, типа "проверь подключение". Чуть позже попробую аналогичную штуку провернуть через эксепшн

2021-07-27 15:02 UTC, Doraepod commented on python/gamepad/utils.py
> -def calc_velocity(x: float, y: float, velocity: float, v_max) -> Union(float, float):
Из-за этой штуки крашилась программа. Сообщение ошибки не запомнил, но что-то вроде, что Union так нельзя использовать. Немного погуглил и как будто Union действительно не совсем об этом. Если убрать, то все заработало.

2021-07-27 15:02 UTC, serykhelena commented on python/gamepad/src/xbox_one.py
> +            return
Ты можешь ловить исключение из класса  в скрипте (через try - except)

2021-07-27 15:04 UTC, serykhelena commented on python/gamepad/utils.py
> -def calc_velocity(x: float, y: float, velocity: float, v_max) -> Union(float, float):
квадратные скобочки нужно `Union[float, float]` тогда должно заработать. А в чём проблема? Что не об этом?

2021-07-27 15:11 UTC, Doraepod commented on python/gamepad/utils.py
> -def calc_velocity(x: float, y: float, velocity: float, v_max) -> Union(float, float):
Ну, как я понял это штука позволяет указать возможные типы возвращаемого значения (например, foo() -> Union[str, int] значит функция вернет строку или инт), а тут идея что возвращаются два значения. Но я вижу это в первый раз и, скорее всего, не прав

2021-07-27 15:13 UTC, serykhelena commented on python/gamepad/utils.py
> -def calc_velocity(x: float, y: float, velocity: float, v_max) -> Union(float, float):
Ты всё верно говоришь. Но ты ведь возвращает tuple, мне кажется, что это тоже самое, что и Union в целом. Если совсем хочешь докапаться, то есть тип `Tuple[float, float]` (=

2021-07-28 12:16 UTC, Doraepod commented on python/gamepad/src/xbox_one.py
> +logging.basicConfig(
вроде все лишнее убрал

2021-07-28 12:16 UTC, Doraepod commented on python/gamepad/src/xbox_one.py
> +logger = logging.getLogger(__name__)
Сделано

2021-07-28 12:17 UTC, Doraepod commented on python/gamepad/src/xbox_one.py
> +            return
Сделал аналогично. 5 попыток прочитать устройство, потом останавливается, если не удалось

2021-07-28 12:20 UTC, Doraepod commented on python/gamepad/utils.py
> -def calc_velocity(x: float, y: float, velocity: float, v_max) -> Union(float, float):
Да, основная проблема была с тем, что union[float, float] это то же самое, что и просто float (так как или float или float). Сейчас указал возвращаемый тип кортеж (float, float). Чтобы починить исходную конструкцию можно поставить union[(float, float)], но мне это показалось избыточным.

2021-07-28 14:11 UTC, serykhelena approved these changes

2021-07-28 14:11 UTC, serykhelena commented on python/gamepad/wireless_control.py
> +    for _ in range(5):
а зачем 5 раз проверять? Т.е. получается максимально  15 сек на подключение джойстика?

2021-07-28 14:11 UTC, serykhelena commented on python/gamepad/wireless_control.py
> +            dev = Gamepad()
после dev можно добавить break и тогда строки 124 и 125 можно удалить... мне лично так было бы проще читать..

2021-07-28 14:13 UTC, serykhelena commented on python/gamepad/src/xbox_one.py
> +        self._logger = self._logger = logging.getLogger(self.__class__.__name__)
опечатка - два раза self._logger = self._logger

2021-07-28 14:15 UTC, serykhelena commented on python/gamepad/utils.py
> +def calc_velocity(x: float, y: float, velocity: float, v_max: float) -> tuple[float, float]:
нужно сделать импорт
from typing import Tuple 
и с большой буквы написать, иначе опять ругаться будет

2021-07-28 14:21 UTC, Doraepod commented on python/gamepad/wireless_control.py
> +            dev = Gamepad()
Да, это здорово. Не подумал что можно без else

2021-07-28 14:21 UTC, Doraepod commented on python/gamepad/src/xbox_one.py
> +        self._logger = self._logger = logging.getLogger(self.__class__.__name__)
Поправил

2021-07-28 14:37 UTC, Doraepod commented on python/gamepad/utils.py
> +def calc_velocity(x: float, y: float, velocity: float, v_max: float) -> tuple[float, float]:
Сделал, но тут я не очень понял. Во всех трех вариантах ( -> Tuple[float, float], -> tuple[float, float], -> (float, float) ) он не ругается и понимает, что функция возращает кортеж. В третьем варианте как будто он останавливался только на самом факте наличия кортежа, а типы игнорировал. То есть если сделать такую функцию

def foo(a: int, b: float) -> (float, float):
    return a, b

он ворнингов не показывает, но при наведении на функцию утверждает, что она возвращает (int, float). В обоих других вариантах все работает, как будто, без разницы, но правильно. Это странно, так как я считал, что (1, 2) и tuple[1, 2] это фактически одно и тоже, но, судя по всему, это не так. По крайней мере у получившихся объектов разные типы.

P.S. сейчас понял, что правильно кортеж собирать как tuple([1, 2]). В этом случае возникает та же ситуация, что и в случае с -> (float, float). На выходе получает просто tuple и принимает это за тип, игнорируя содержимое. Непонятно почему tuple[float, float] корректно работал. Наверное, надо понимать что такое <class 'types.GenericAlias'>

2021-07-28 14:40 UTC, Doraepod commented on python/gamepad/wireless_control.py
> +    for _ in range(5):
Ну чтобы не сразу скрипт падал, а можно было увидеть и включить уснувший контроллер. За 15 секунд вроде вполне реально. Если найти какую-нибудь пьезопищалку, можно напоминать звуком. Ну или колонку вернуть и начать орать.

2021-07-28 14:44 UTC, merged